. ~/.bashrc

export PATH="$PATH:~/.gem/ruby/2.3.0/bin"
export GEM_HOME="$HOME:~/.gem"

export DATO_DEPLOY_TOKEN={{ vault_dato_deploy_token }}
export DATO_API_TOKEN={{ vault_dato_api_token }}

export NODE_ENV={{ node_env }}
export MAILGUN_API_KEY={{ vault_mailgun_api_key }}
export MAILGUN_DOMAIN={{ domain }}
export INFO_EMAIL={{ info_email }}
export WEBMASTER_EMAIL={{ webmaster_email }}
export RAVEN_DSN={{ vault_raven_dsn }}
