---

- hosts: all
  vars_files:
    - vars.yml
  remote_user: vagrant
  sudo: no

  tasks:

    - name: checkouts the dynamic repository
      git: repo=https://github.com/{{ github_user_name }}/{{ user }}.website.dynamic.git dest=/home/{{ user }}/{{ user }}.website.dynamic
      sudo_user: "{{ user }}"
      sudo: yes

    - name: checkouts the static repository
      git: repo=https://github.com/{{ github_user_name }}/{{ user }}.website.static.git dest=/home/{{ user }}/{{ user }}.website.static
      sudo_user: "{{ user }}"
      sudo: yes

    - name: checkouts the jekyll-hook repository
      git: repo=https://github.com/developmentseed/jekyll-hook.git dest=/home/{{ user }}/jekyll-hook
      sudo_user: "{{ user }}"
      sudo: yes

    - name: Writes the jekyll config
      template: src=templates/jekyll.j2 dest=/home/{{ user }}/jekyll-hook/conf.json mode=0644
      sudo_user: "{{ user }}"
      sudo: yes

    - name: Ensures that the shared folder is created
      action: file path=/home/{{ user }}/shared state=directory
      sudo_user: "{{ user }}"
      sudo: yes

    - name: install bundler gems
      gem: name=bundler state=present user_install=yes
      sudo_user: "{{ user }}"
      sudo: yes

    - name: Build jekyll
      command: "bundle exec jekyll build"
      sudo_user: "{{ user }}"
      sudo: yes
      environment:
        PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
      args:
        chdir: "/home/{{ user }}/{{ user }}.website.static"
      notify:
       - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
