---

- hosts: all
  become: yes

  vars_files:
    - vars.yml
    - secrets.yml

  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"
      private: no

  roles:
    - common
    - frontend
    - backend

  handlers:
    - name: nginx reload
      service: name=nginx state=reloaded
