---

- hosts: all
  vars_files:
    - vars.yml
  remote_user: vagrant
  sudo: yes

  tasks:

    # - name: update apt
    #   action: command /usr/bin/apt-get update

    - name: add nginx ppa
      action: apt_repository repo=ppa:nginx/stable state=present

    - name: add nodejs ppa
      action: apt_repository repo=ppa:chris-lea/node.js state=present

    - name: install nginx package
      action: apt pkg=nginx state=installed

    - name: install nodejs package
      action: apt pkg=nodejs state=installed

    - name: install git package
      action: apt pkg=git state=installed

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: creates the app user
      user: name={{ user }} group=www-data shell=/bin/bash # generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

    - name: enable colors for root
      command: sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' /root/.bashrc

    - name: enable colors for the new base user
      command: sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' /home/{{ user }}/.bashrc

    - name: writes the nginx site
      template: src=templates/nginx.site.j2 dest=/etc/nginx/sites-available/www.{{ domain }} mode=0644

    - name: install forever package
      npm: name=forever global=yes

    - name: Install system ruby version
      apt: pkg={{ item }} state=present
      with_items:
        - curl
        - ruby

    - name: Install rvm key
      shell: "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"

    - name: Install latest stable ruby version
      shell: "\\curl -sSL https://get.rvm.io | bash -s stable --ruby"

    - name: Remove system ruby version
      apt: pkg= state=absent purge=yes
      with_items:
        - ruby
        - ruby1.9.1
        - libruby1.9.1

    - name: Install bundler
      shell: "gem install bundler"
      environment:
        PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

    - name: install ruby package
      action: apt pkg=ruby1.9.1-dev state=installed

    - name: install jekyll gems
      gem: name=jekyll state=present user_install=no

    - name: ensure apache is running
      service: name=nginx state=started
