---

- hosts: production
  become: yes
  vars_files:
    - vars.yml
    - secrets.yml
  vars:
    domain: '{{ top_domain }}'
    certificates_folder: /etc/letsencrypt/live
    node_env: production
  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"
      private: no

  roles:
    - common
    - frontend
    - backend

  handlers:
    - name: nginx reload
      service: name=nginx state=reloaded
