---

- hosts: production
  remote_user: thegreenvintage
  become: yes
  vars_files:
    - vars.yml
    - secrets.yml
  vars:
    domain: thegreenvintage.com
    certificates_folder: /etc/letsencrypt/live
    node_env: production
  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"

  roles:
    - common
    - frontend
    - backend
    - role: vendor/ansible-letsencrypt
      letsencrypt_webroot_path: '/home/{{ user }}/shared/public/{{ user }}.website.static'
      letsencrypt_email: 'info@{{ domain }}'
      letsencrypt_cert_domains:
        - 'www.{{ domain }}'
        - 'next.{{ domain }}'
        - '{{ domain }}'
      letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
      when: create_certificates == 'yes'
