#!/bin/bash -l

set -e

WWW=$HOME/shared/public
GIT_REPO=$HOME/shared/repositories/dynamic
PUBLIC_PROD_WWW=$WWW/dynamic
PUBLIC_NEXT_WWW=$WWW/next.dynamic

read GIT_FROM GIT_TO GIT_BRANCH
GIT_BRANCH=$(echo "$GIT_BRANCH" | sed 's/refs\/heads\///')

if [ "$GIT_BRANCH" == "master" ]; then
  PUBLIC_WWW=$PUBLIC_PROD_WWW
  SERVICE=$USER.backend
else
  PUBLIC_WWW=$PUBLIC_NEXT_WWW
  SERVICE=next.$USER.backend
fi


echo 'Restarting node service...'

# Fix downtime
rm -Rf "$PUBLIC_WWW"

git clone -b "$GIT_BRANCH" "$GIT_REPO" "$PUBLIC_WWW"

cd "$PUBLIC_WWW"
npm install

cd "$HOME/shared/config"
pm2 startOrReload "$USER.config.js" --only "$SERVICE"

exit
