---
  - stat: path=/home/{{ user }}/shared/public/dynamic
    register: backend

  - name: initialize backend
    become_user: '{{ user }}'
    when: backend.stat.exists == False
    git:
      repo: /home/{{ user }}/shared/repositories/dynamic
      dest: /home/{{ user }}/shared/public/dynamic
      version: master

  - name: installing package.json dependencies
    become_user: '{{ user }}'
    command: npm install
    args:
      chdir: /home/{{ user }}/shared/public/dynamic


  - stat: path=/home/{{ user }}/shared/public/next.dynamic
    register: nextbackend

  - name: initialize next backend
    become_user: '{{ user }}'
    when: nextbackend.stat.exists == False
    git:
      repo: /home/{{ user }}/shared/repositories/dynamic
      dest: /home/{{ user }}/shared/public/next.dynamic
      version: master # Override in future deploys

  - name: installing package.json dependencies in next
    become_user: '{{ user }}'
    command: npm install
    args:
      chdir: /home/{{ user }}/shared/public/next.dynamic



  - name: pm2 config for backend
    become_user: '{{ user }}'
    template: src=templates/pm2.config dest=/home/{{ user }}/shared/config/{{ user }}.config.js mode=0640

  - name: starting backend services
    become_user: '{{ user }}'
    notify: nginx reload
    command: pm2 startOrReload {{ user }}.config.js
    args:
      chdir: /home/{{ user }}/shared/config
