---
  - name: environment variables
    template: src=templates/bash_profile dest=/home/{{ user }}/.bash_profile mode=0644

  - name: Import the NodeSource GPG key into apt
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: add nodejs ppa
    action: apt_repository repo='deb https://deb.nodesource.com/node_5.x trusty main' state=present

  - name: install nodejs package
    action: apt pkg=nodejs state=installed

  - name: install pm2 package
    npm: name=pm2 global=yes

  - name: starting backend service
    become_user: '{{ user }}'
    command: pm2 start ./bin/www --name {{ user }}.backend
    args:
      chdir: /home/{{ user }}/shared/public/{{ user }}.website.dynamic
    environment:
      PORT: /home/{{ user }}/shared/{{ user}}.website.dynamic.sock

  - name: starting next backend service
    become_user: '{{ user }}'
    command: pm2 start ./bin/www --name next.{{ user }}.backend
    args:
      chdir: /home/{{ user }}/shared/public/next.{{ user }}.website.dynamic
    environment:
      PORT: /home/{{ user }}/shared/next.{{ user}}.website.dynamic.sock
