---
  - name: environment variables
    become_user: '{{ user }}'
    template: src=templates/bash_profile dest=/home/{{ user }}/.bash_profile mode=0640

  - name: install pm2 package
    npm: name=pm2 global=yes
