---

  - name: CSP
    set_fact:
      csp_default:
        - "'self'"
      csp_script:
        - "'self'"
        - "'unsafe-inline'"
        - "'unsafe-eval'"
        - https://www.google-analytics.com
        - https://maps.googleapis.com
        - https://cdnjs.cloudflare.com
      csp_img:
        - "'self'"
        - https://www.google-analytics.com
        - https://maps.googleapis.com
        - https://maps.gstatic.com
        - https://csi.gstatic.com
      csp_style:
        - "'self'"
        - "'unsafe-inline'"
        - https://fonts.googleapis.com
        - https://cdnjs.cloudflare.com
      csp_font:
        - "'self'"
        - https://fonts.googleapis.com
        - https://fonts.gstatic.com
        - https://cdnjs.cloudflare.com
      csp_frame:
        - https://www.youtube.com
      csp_child:
        - https://www.youtube.com
      csp_object:
        - "'none'"
      csp_connect:
        - "'self'"
