---

  - name: CSP
    set_fact:
      csp_rules:
        default-src:
          - "'self'"
        script-src:
          - "'self'"
          - "'unsafe-inline'"
          - "'unsafe-eval'"
          - https://www.google-analytics.com
          - https://maps.googleapis.com
          - https://cdnjs.cloudflare.com
        img-src:
          - "'self'"
          - https://www.google-analytics.com
          - https://maps.googleapis.com
          - https://maps.gstatic.com
          - https://csi.gstatic.com
        style-src:
          - "'self'"
          - "'unsafe-inline'"
          - https://fonts.googleapis.com
          - https://cdnjs.cloudflare.com
        font-src:
          - "'self'"
          - https://fonts.googleapis.com
          - https://fonts.gstatic.com
          - https://cdnjs.cloudflare.com
        frame-src:
          - https://www.youtube.com
        child-src:
          - https://www.youtube.com
        object-src:
          - "'none'"
        connect-src:
          - "'self'"
