---

  - name: Install Ruby 2.3 package
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - 'software-properties-common'
      - 'ruby2.3'
      - 'ruby2.3-dev'

  - name: install bundler gems
    gem:
      executable: /usr/bin/gem2.3
      name: bundler
      state: latest
      user_install: no
