---
  - name: Add SSH keys to `ubuntu` user
    authorized_key:
      user: ubuntu
      key: '{{ item }}'
    with_file:
      - public_keys/fcsonline

  - name: Add SSH keys to domain user
    authorized_key:
      user: '{{ user }}'
      key: '{{ item }}'
    with_file:
      - public_keys/fcsonline
