---
  - name: Install apt https package
    action: apt pkg=apt-transport-https state=installed

  - name: Install common packages
    apt:
      name: '{{ item }}'
      state: present
      update_cache: yes
    with_items:
      - 'build-essential'
      - 'ca-certificates'
      - 'git'
